audit_header: false
title: San Diego Mortgage Video Blog with PrimeLending
description: Our mission at PrimeLending is to be your best resource for the San Diego mortgage process. Whether you’re a first-time homebuyer, in the market for another home, or you’re looking to renovate or refinance, PrimeLending makes your process simple, transparent and rewarding. For us, it really is Home Loans Made Simple®.
show_custom_links: false
custom_links:
  - title: Download Checklist
    url: https://drive.google.com/open?id=1asKI2GToeHBUq5glJEF8CD7jaA76N4_n
show_custom_links_new_tab: false
custom_links_new_tab:
  - title: Apply Now
    url: https://apply.primelending.com/andre.kwan/SPAs/UserLogin/index.html

client:
  name: PrimeLending
  title:
  license_number: 'NMLS# 13649'
  about_markdown: |
    At the heart of your PrimeLending experience is a personal relationship with a home loan expert who will guide you through each step of the mortgage process. In fact, our entire team of more than 2,800 passionate employees located throughout the United States are focused on helping to turn your homeownership goals into a reality.

    Since 1986, we’ve been working together to have a profound and positive impact on the lives of all we serve. From application through closing, you’ll feel a difference when you work with the PrimeLending team. You can count on us to provide clear communication, timely responses, valuable insight and quick results.
  brand: PrimeLending
  brokerage:
  market: San Diego
  address: 4747 Executive Drive Suite 520<br>San Diego, CA 92121
  phone: toll-free 1-800-887-6174
  phone_type:
  phone2:
  phone2_type:
  email: socal@primelending.com
  url: https://lo.primelending.com/sandiego/

CTAs:
  first_CTA_text: Request Consultation
  first_CTA_URL: https://lo.primelending.com/mradi/about/contact-me
  second_CTA_text: Apply For A Loan
  second_CTA_URL: https://apply.primelending.com/mradi/SPAs/UserLogin/index.html#/userLogin

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Contact Us"
    CTA_text: "Lets Talk! We can help you."
    CTA_link_text: "Request Consultation"
    CTA_url: https://lo.primelending.com/mradi/about/contact-me

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "The PrimeLending Experience"
    CTA_text2: "Learn about different types of loans."
    CTA_link_text2: "Loan Types"
    CTA_url2: https://lo.primelending.com/mradi/home-loans/types-of-loans

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/san-diego-real-estate-podcast-with-andre-kwan/id1481265566

podcast:
  title: 'San Diego Real Estate Podcast with Andre Kwan'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Diego Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from PrimeLending - your professional San Diego Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Diego, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Andre Kwan'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: San Diego Mortgage Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#bf2e1b'
  theme_color: '#5a5b5d'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#0F3A43'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
