audit_header: false
title: San Diego Mortgage Video Blog with PrimeLending
description: Our mission at PrimeLending is to be your best resource for the San Diego mortgage process. Whether you’re a first-time homebuyer, in the market for another home, or you’re looking to renovate or refinance, PrimeLending makes your process simple, transparent and rewarding. For us, it really is Home Loans Made Simple®.
show_custom_links: false
custom_links:
  - title: Download Checklist
    url: https://drive.google.com/open?id=1asKI2GToeHBUq5glJEF8CD7jaA76N4_n
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: Our Team
    url: https://lo.primelending.com/sandiego/#branchLoList

client:
  name: PrimeLending
  title:
  license_number: 'NMLS# 1833692'
  about_markdown: |
    At the heart of your PrimeLending experience is a personal relationship with a home loan expert who will guide you through each step of the mortgage process. In fact, our entire team of more than 2,800 passionate employees located throughout the United States are focused on helping to turn your homeownership goals into a reality.

    Since 1986, we’ve been working together to have a profound and positive impact on the lives of all we serve. From application through closing, you’ll feel a difference when you work with the PrimeLending team. You can count on us to provide clear communication, timely responses, valuable insight and quick results.
  brand: PrimeLending San Diego
  brokerage:
  market: San Diego
  address: 3131 Camino Del Rio N, Suite 1620<br>San Diego, CA 92108
  phone: Toll-Free 1-800-887-6174
  phone_type:
  phone2:
  phone2_type:
  email: socal@primelending.com
  url: https://lo.primelending.com/sandiego/

CTAs:
  first_CTA_text: Apply For A Loan
  first_CTA_URL: https://apply.primelending.com/mradi/SPAs/UserLogin/index.html#/userLogin
  # second_CTA_text: Apply For A Loan
  # second_CTA_URL: https://apply.primelending.com/mradi/SPAs/UserLogin/index.html#/userLogin

sidebar_CTA:
  - CTA_image_path: /img/cta-images/002.jpg
    CTA_title: "The PrimeLending Experience"
    CTA_text: "Learn about different types of loans."
    CTA_link_text: "Loan Types"
    CTA_url: https://lo.primelending.com/sandiego/our-process

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "The PrimeLending Experience"
#     CTA_text2: "Learn about different types of loans."
#     CTA_link_text2: "Loan Types"
#     CTA_url2: https://lo.primelending.com/mradi/home-loans/types-of-loans

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/SoCal-Primelending-112192456794353/
  linkedin_url: https://www.linkedin.com/company/socal-primelending/?viewAsMember=true
  youtube_url: https://www.youtube.com/channel/UCkpJou7L58V6Ncmeb5VVdUw
  twitter_url:
  instagram_url: https://www.instagram.com/socalprimelending/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/san-diego-real-estate-podcast-with-andre-kwan/id1481265566

podcast:
  title: 'San Diego Mortgage Podcast with Andre Kwan'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'PrimeLending(NMLS 13649). Views do not represent Hilltop Holdings, PlainsCapital or subsidiaries. Equal Housing Lender. www.primelending.com'
  description: 'Featuring Mike Radi(NMLS 188397), Andre Kwan(NMLS 188589), Erik Sandstom(NMLS 805941), Kenia Costa(NMLS 536257), Luis Carranza(NMLS 502320), Mike Fransisco(NMLS 159895) Views do not represent Hilltop Holdings, PlainsCapital or subsidiaries. Equal Housing Lender. www.primelending.com'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Diego, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Andre Kwan'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: San Diego Mortgage Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#be301a'
  theme_color: '#595a5e'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#067f88'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#be301a'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
